config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations", sessions: "sessions" }
  root to: 'home#index'
  post 'online', to: 'home#online'
  post 'offline', to: 'home#offline'

  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
    get 'register', to: 'devise/registrations#new'
    delete 'logout', to: 'sessions#destroy'
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :avatar

  enum state: { offline: 0, online: 1 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.where.not(id: current_user.id) if user_signed_in?
  end

  def online
    current_user.online!
    broadcast_change_to_users("online")
    respond_to do |format|
        format.js
    end
  end

  def offline
    current_user.offline!
    broadcast_change_to_users("offline")
    respond_to do |format|
        format.js
    end
  end
  
  
  private 

  def broadcast_change_to_users(state)
    ActionCable.server.broadcast(
        "appearance",
        state: state,
        user_id: current_user.id
    )
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  
  private

  def sign_up_params
    params.require(:user).permit(:name, :email, :avatar, :github_link, :password)
  end

  def account_update_params
    params.require(:user).permit(:name, :email, :github_link, :avatar, :password)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < Devise::SessionsController

  def destroy
    if current_user.online?
      current_user.offline!
      broadcast_change_to_users("offline") 
    end
    
    super
  end

  private

  def broadcast_change_to_users(state)
    ActionCable.server.broadcast( 
      "appearance", 
      state: state, 
      user_id: current_user.id      
    ) 
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper

  def developers
    if user_signed_in?
      'home/partials/developers'
    else
      'home/partials/empty'
    end
  end

  def links
    if user_signed_in?
      'home/partials/nav/dropdown'
    else
      'home/partials/nav/auth_links'
    end
  end

  def change_state_btn
    current_user.online? ? "home/partials/nav/dropdown/gofflinebtn" :"home/partials/nav/dropdown/gonlinebtn" 
  end

  def btnStart
    if user_signed_in?
      "home/partials/startbtn/scrollbtn"
    else
      "home/partials/startbtn/authbtn"
    end
  end

end

app/views/home/index.html.erb
<%= render 'home/partials/nav' %> 
<%= render 'home/partials/header' %> 
<%= render developers %>

app/views/home/offline.js.erb
var onlineBtn = document.getElementById("js-onlinebtn")
onlineBtn.classList.add("d-none") 

var offlineBtn = document.getElementById("js-offlinebtn")
offlineBtn.classList.remove("d-none")

app/views/home/online.js.erb
var offlineBtn = document.getElementById("js-offlinebtn")
offlineBtn.classList.add("d-none")

var onlineBtn = document.getElementById("js-onlinebtn")
onlineBtn.classList.remove("d-none")

app/views/home/partials/_developers.html.erb
<section class="developers text-center" id="js-developers">
  <h2 class="title">No appointment needed. Just chat!</h2>
  <div class="container">
    <div class="row my-5">
      <% @users.each do |user| %>

        <div class="col-md-3 col-xs-6">
          <%= render 'home/partials/user-card', user: user %>
        </div>

      <% end %>
    </div>
  </div>
</section>

app/views/home/partials/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">     
  <div class="container">         
    <a class="navbar-brand" href="#"><i class="fas fa-adjust"></i>Navbar</a>         
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">           
      <span class="toggler"><i class="fas fa-bars text-white"></i></span>         
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">           
      <ul class="navbar-nav ml-auto">             
        <%= render links %>           
      </ul>         
    </div>     
  </div>
</nav>

<div class="jumbotron jumbotron-fluid mb-0">
  <div class="container">
    <div class="update">
      <p class="py-1 px-2">
        <span class="soon mx-2 p-1">SOON</span>TextChat: Instant text messaging coming out soon <i class="fas fa-chevron-right"></i>
      </p>
    </div>
    <h1 class="display-4 text-white">The right way to chat with developers, globally</h1>
    <p class="lead mb-5">
      Have an idea to share? Need help with a coding challenge? 
      Come chat with your fellow developers.
      Do it automatically and around the globe with DevTime. No appointment needed!
    </p>
    <div class="buttons">
      <%= render btnStart %>
      <a href="#" class="btn btn-primary disabled">TextChat coming soon!!!</a>
    </div>
  </div>
</div>
<div class="text-right">
  <img src="<%= image_path('Workathome.png') %>" alt="" class="header-image d-none d-md-block mt-3">
</div>

app/views/home/partials/_user-card.html.erb
<div class="dev-card p-3 my-3 text-center">
  <% if user.avatar.attached? %>
    <%= image_tag user.avatar %>
  <% else %>
    <img src="assets/avatar5.jpeg" alt="">
  <% end %>

  <h6 class="dev-name text-white">
    <%= user.name  %>
    <span class="appearance <%= user.state %>" id="js-appearance<%= user.id %>">             
      <i class="fas fa-circle"></i>         
    </span>
  </h6>
  <div class="dev-icons">         
    <%= link_to user.github_link, class:'github-icon m-2', title: "Github page", data: {toggle: "tooltip", placement: "top"} do %>           
      <iclass="fab fa-github-square"></i>         
    <% end %>         
    <%= link_to '', class:"camera-icon m-2 #{user.state}", id:"js-camera-icon#{user.id}", 
        title: "Start a video call with #{user.name}", 
        data: {id: user.id, name: user.name, toggle: "tooltip", placement: "top"}, 
        remote: true  do %>           
          <i class="fas fa-video"></i>         
      <% end %>     
  </div>
</div>

app/views/home/partials/modals/_receiver_notif_modal.html.erb
<div class="modal fade" id="receiver-notif-modal" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-sm modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h6 class="modal-title" id="exampleModalLabel">Incoming video call</h6>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <span><strong id="sender_name"></strong> is calling</span>
        <%= link_to '', id:'answer-call' do %>
          <i class="fas fa-video"></i>
        <% end %>
        <h6 id="session_id"></h6>
        <h6 id="sender_id"></h6>
      </div>
    </div>
  </div>
</div> 

app/views/home/partials/modals/_sender_notif_modal.html.erb
<div class="modal fade" id="sender-notif-modal" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-sm modal-dialog-centered">
    <div class="modal-content">

      <div class="modal-body">
        <span>Calling <strong id="recipient_name_modal"></strong></span>
        <% 3.times do %>
            <div class="spinner-grow text-info" role="status">
              <span class="sr-only">Loading...</span>
            </div>
        <% end %>
      </div>

    </div>
  </div>
</div> 

app/views/home/partials/modals/_session_modal.html.erb
<div class="modal fade" id="session-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <%= link_to '', class:"modal-title", id:"stop-session" do %>
          <i class="fas fa-video-slash"></i>
        <% end %>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body" id="modal-body-session">
        <div class="session">
          <div id="subscriber">

          </div>
          <div id="publisher">

          </div>
        </div>
      </div>

    </div>
  </div>
</div>

</div> 

app/views/home/partials/nav/_auth_links.html.erb
<li class="nav-item">     
  <%= link_to 'Sign Up', register_path, class: 'nav-link signup-btn btn btn-success py-1 mx-3', data: {turbolinks: false} %>
</li>
<li class="nav-item">     
  <%= link_to 'Log In', login_path, class: 'nav-link mx-3' %>
</li>

app/views/home/partials/nav/_dropdown.html.erb
<li class="nav-item"><%= render change_state_btn %></li> 

<li class="nav-item dropdown">     
  <a class="nav-link mx-3 dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"  aria-haspopup="true" aria-expanded="false">         
    <%= current_user.name %>     
  </a>         
  <div class="dropdown-menu" aria-labelledby="navbarDropdown">             
    <%= link_to 'Logout', logout_path, class: 'dropdown-item', method: :delete %>         
  </div>
</li>

app/views/home/partials/nav/dropdown/_gofflinebtn.html.erb
<%= link_to 'You are online', offline_path, class: 'nav-link state-btn online mx-3 btn btn-success', id: 'js-onlinebtn', remote: true, method: :post %> 
<%= link_to 'Go Online', online_path, class: 'nav-link state-btn offline d-none mx-3 btn btn-outline-success', id: 'js-offlinebtn', remote: true, method: :post %>

app/views/home/partials/nav/dropdown/_gonlinebtn.html.erb
<%= link_to 'Go Online', online_path, class: 'nav-link state-btn offline mx-3 btn btn-outline-success', id: 'js-offlinebtn', remote: true, method: :post %> 
<%= link_to 'You are online', offline_path, class: 'nav-link state-btn online d-none mx-3 btn btn-success', id: 'js-onlinebtn', remote: true, method: :post %>

app/views/home/partials/startbtn/_authbtn.html.erb
<%= link_to 'Start now', login_path, class: 'start-btn btn btn-success mr-1', id: 'js-start-btn-auth' %>

app/views/home/partials/startbtn/_scrollbtn.html.erb
<%= link_to 'Start now', '#', class: 'start-btn btn btn-success mr-1', id: 'js-start-btn' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Final</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.min.css">
    <link href="https://fonts.googleapis.com/css?family=Muli:300,400,500,600,700,800&display=swap" rel="stylesheet">
  </head>

  <body>
    <!-- Devise notification styled with bootstrap -->
    <% if notice %>
          <div class="notice alert alert-success alert-dismissible fade show" role="alert">
            <%= notice %>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
    <% elsif alert %>
          <div class="danger alert alert-danger alert-dismissible fade show" role="alert">
            <p><%= alert %></p>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
    <% end %>    

    <%= yield %>
    
    <%= render 'home/partials/modals/receiver_notif_modal' %>
    <%= render 'home/partials/modals/sender_notif_modal' %>
    <%= render 'home/partials/modals/session_modal' %>
    
    <script src="https://static.opentok.com/v2/js/opentok.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://static.opentok.com/v2/js/opentok.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>